### PR TITLE
Remove dependency on rgeos

### PR DESCRIPTION
**Pull request by hafen**
This PR removes the dependency on rgeos which is being retired (#42).

@jbaileyh is this something you can test and submit to CRAN if it looks good to you?

### CODE REVIEW

**Comment by hafen** [comment]
Maybe we should look at merging and testing #37 while we're at it.

**Comment by hafen** [comment]
I just wanted to check back in on this. @jbaileyh let me know if you are not in a position to maintain this anymore.

Also @aecoleman, if you have bandwidth, could you look into integrating your PR into this one?

**Comment by aecoleman** [comment]
@hafen Let me see if I can find some time this weekend to take a look...

**Comment by jbaileyh** [comment]
@aecoleman, @hafen thanks so much for your time and effort with this. I'm not currently in a position to maintain this at present. Is there anything that I can do to support a handover etc?

**Comment by hafen** [comment]
> @aecoleman, @hafen thanks so much for your time and effort with this. I'm not currently in a position to maintain this at present. Is there anything that I can do to support a handover etc?

@jbaileyh if you'd like I can take on the maintainer role. From what I understand, all that needs to happen is that you need to send an email to CRAN@R-project.org letting them know that you are passing on the role of maintainer to me. Feel free to cc me rhafen@gmail.com. They expect to see the email from you come from the address listed in the DESCRIPTION file.

Once you have sent this email, I should be able to submit new versions of the package to CRAN and deal with all of the submission process. You will remain author and creator and I will be a maintainer and contributor.

**Comment by jbaileyh** [comment]
Hi @hafen I have submitted the email as suggested. Thanks for your kind offer. Please let me know if there's anything else I need to do with this repo to facilitate your maintenance. 👍

**Pull request closed without merging**
